version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=123
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    command: sh -c "alembic upgrade head && uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  pg_data:
