"""changes in id_seq accepted

Revision ID: d954fd6908d5
Revises: d0632c8c1122
Create Date: 2024-04-07 16:28:29.559742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd954fd6908d5'
down_revision: Union[str, None] = 'd0632c8c1122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
