"""adv model FK added

Revision ID: b4dd97162dba
Revises: 592802b85dac
Create Date: 2024-04-06 19:23:10.899875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4dd97162dba'
down_revision: Union[str, None] = '592802b85dac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('advertisement_author_id_fkey', 'advertisement', type_='foreignkey')
    op.create_foreign_key(None, 'advertisement', 'user', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'advertisement', type_='foreignkey')
    op.create_foreign_key('advertisement_author_id_fkey', 'advertisement', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###
