"""adv model changed

Revision ID: 592802b85dac
Revises: 6db0e10663ff
Create Date: 2024-04-06 12:44:34.739267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '592802b85dac'
down_revision: Union[str, None] = 'a7246e09f475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisement', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'advertisement', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'advertisement', type_='foreignkey')
    op.drop_column('advertisement', 'author_id')
    # ### end Alembic commands ###
