"""adv model author added

Revision ID: 6db0e10663ff
Revises: 3a4ef5c9399e
Create Date: 2024-04-06 12:18:51.433316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6db0e10663ff'
down_revision: Union[str, None] = '3a4ef5c9399e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisement',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('title', sa.String(length=50), nullable=False),
                    sa.Column('body', sa.String(length=2500), nullable=True),
                    sa.Column('group', sa.Enum('SELLING_ADV', 'BUYING_ADV', 'SERVICE_ADV', name='group'),
                              nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_advertisement_id'), 'advertisement', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
